services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: produtos_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  gerenciamento-produtos:
    build: ./gerenciamento-produtos
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/produtos_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./servico-a/src/main/resources:/app/resources

  consumo-produto:
    build: ./consumo-produto
    ports:
      - "8082:8082"
    depends_on:
      - gerenciamento-produtos

volumes:
  mysql-data:
